name: Docs

on:
  push:
    branches: docs

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - run: cargo doc
        env:
          RUSTDOCFLAGS: "--document-private-items --default-theme=ayu --deny warnings"
      - run: cp docs/* target/doc
      - uses: actions/upload-pages-artifact@v1
        with:
          path: 'target/doc'
      - uses: actions/configure-pages@v3
      - uses: actions/deploy-pages@v1
        id: deployment
